; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]


; Espressif ESP32 platform
platform = espressif32
; ESP32-S3-DevKitC-1 board definition
; Physical board is N16R8V; memory is configured through menuconfig
board = esp32-s3-devkitc-1
; Use native ESP-IDF framework instead of arduino framework
framework = espidf




; Serial monitor speed
monitor_speed = 115200
; Firmware upload speed
upload_speed = 921600




; ESP32-S3 microcontroller
board_build.mcu = esp32s3
; Maximum CPU frequency
board_build.f_cpu = 240000000L




; Tell the build system that the board has PSRAM
build_flags =
    -DBOARD_HAS_PSRAM



